version: '3.9'


services:
  db:
    image: postgres:14-alpine
    ports:
      - ${POSTGRES_EXPOSE_PORT}:5432
    
    environment:
      - TZ: "${POSTGRES_TZ}"
      - POSTGRES_USER: "${POSTGRES_USER}"
      - POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      - POSTGRES_DB: "${POSTGRES_DB}"
    
    volumes:
      - ./data/db:/var/lib/postgresql/data/

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    
    ports:
      - ${FRONTEND_EXPOSE_PORT}:3000
    
    volumes:
      - ./frontend:/app/frontend

    depends_on:
      - backend

  backend: 
    build: 
      context: ./backend
      dockerfile: Dockerfile
    
    environment:
      - POSTGRES_USER: "${POSTGRES_USER}"
      - POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      - POSTGRES_DB: "${POSTGRES_DB}"
    
    ports:
      - ${DJANGO_EXPOSE_PORT}:8000

    volumes:
      - ./backend:/app/backend

    depends_on:
      - db
